import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import rankings from "./data";
import Rank from "./Rankings";

export default function Home() {
  return (
    <>
      <Head>
        <title>Offical PITA Rankings</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="//cloud.typenetwork.com/projects/4237/fontface.css/"
          rel="stylesheet"
          type="text/css"
        ></link>
      </Head>

      <div className={styles.marquee}>{/* marquee code goes in here */}</div>

      <main className={styles.main}>
        <section className={styles.intro}>
          <h1
            className={`${styles.title} ${styles.poynteroldstyledisplaynarrowregular}`}
          >
            The official rankings guide of the different types of PITAs (pains
            in the ass) you can and will encounter at work.
          </h1>
        </section>

        <section className={styles.rankings}>
          {/* Rankings component */}
          {rankings.map((rank) => {
            return <Rank key={rank.id} {...rank}></Rank>;
          })}
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  );
}
