import React, { useRef } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import rankings from "./data";
import Rank from "./Rank";
import Marquee from "./Marquee";

export default function Home() {
  return (
    <>
      <Head>
        <title>Offical PITA Rankings</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="//cloud.typenetwork.com/projects/4237/fontface.css/"
          rel="stylesheet"
          type="text/css"
        ></link>
      </Head>

      <Marquee />

      <main className={styles.main}>
        <section className={styles.intro}>
          <h1
            className={`${styles.title} ${styles.poynteroldstyledisplaynarrowregular}`}
          >
            The official rankings guide of the different types of PITAs (pains
            in the ass) you can and will encounter at work.
          </h1>
        </section>

        <section className={styles.rankings}>
          {rankings.map((rank) => {
            return <Rank key={rank.id} {...rank}></Rank>;
          })}
        </section>
      </main>

      <footer className={styles.footer}>
        <a href="#">About PITAs</a>
        <a href="#">made by @1aurapadilla</a>
        <button href="#">Go Dark</button>
      </footer>
    </>
  );
}
